--CLEAN UP SCRIPT
set serveroutput on
declare
    v_table_exists varchar(1) := 'Y';
    v_sql varchar(2000);
begin
   dbms_output.put_line('Start schema cleanup');
   for i in (select 'TRANSIT' table_name from dual union all
             select 'WALLET' table_name from dual union all
             select 'TICKET' table_name from dual union all
             select 'STATION' table_name from dual union all
             select 'CARD' table_name from dual union all
             select 'RECHARGE_DEVICE' table_name from dual union all
             select 'RECHARGE' table_name from dual union all
             select 'PASS' table_name from dual union all
             select 'PASS_TYPE' table_name from dual union all
             select 'LINE' table_name from dual union all
             select 'TRANSACTION_DEVICE' table_name from dual union all
             select 'TRANSACTION' table_name from dual union all
             select 'LINE_STATION_CONNECTIONS' table_name from dual union all
             select 'OPERATIONS' table_name from dual

   )
   loop
   dbms_output.put_line('....Dropping table '||i.table_name);
   begin
       select 'Y' into v_table_exists
       from USER_TABLES
       where TABLE_NAME=i.table_name;

       v_sql := 'drop table '||i.table_name || ' cascade constraints';
       execute immediate v_sql;
       dbms_output.put_line('........Table '||i.table_name||' dropped successfully');
       
   exception
       when no_data_found then
           dbms_output.put_line('........Table already dropped');
   end;
   end loop;
   dbms_output.put_line('Schema cleanup successfully completed');
exception
   when others then
      dbms_output.put_line('Failed to execute code:'||sqlerrm);
end;
/

-- TABLE CREATION

CREATE TABLE TRANSIT (transit_id number GENERATED BY DEFAULT AS IDENTITY, name varchar(30), status varchar2(8), start_date date, price_per_ride float, PRIMARY KEY(transit_id), CONSTRAINT transit_status_options CHECK (status in ('Active','Inactive')));
CREATE TABLE WALLET(wallet_id number GENERATED BY DEFAULT AS IDENTITY, wallet_type varchar2(6), wallet_expiry date, start_date date, status varchar2(8), PRIMARY KEY(wallet_id), CONSTRAINT wallet_type_options CHECK (wallet_type in ('Card','Ticket')), CONSTRAINT wallet_status_options CHECK (status in ('Active','Inactive')));
CREATE TABLE TICKET(ticket_id number GENERATED BY DEFAULT AS IDENTITY, wallet_id number, rides number, transit_id number, PRIMARY KEY(ticket_id), FOREIGN KEY(wallet_id) REFERENCES WALLET(wallet_id), FOREIGN KEY(transit_id) REFERENCES TRANSIT(transit_id));
CREATE TABLE STATION (station_id number GENERATED BY DEFAULT AS IDENTITY, name varchar (30), construction_date date, PRIMARY KEY(station_id));
CREATE TABLE CARD(card_id number GENERATED BY DEFAULT AS IDENTITY, Balance number, wallet_id number, PRIMARY KEY(card_id), FOREIGN KEY(wallet_id) REFERENCES WALLET(wallet_id));
CREATE TABLE RECHARGE_DEVICE(recharge_device_id number GENERATED BY DEFAULT AS IDENTITY, station_id number, status varchar2(8), PRIMARY KEY(recharge_device_id), FOREIGN KEY (station_id) REFERENCES STATION(station_id),  CONSTRAINT recharge_device_status_options CHECK (status in ('Active','Inactive')));
CREATE TABLE RECHARGE(recharge_id number GENERATED BY DEFAULT AS IDENTITY, value_of_transaction number, wallet_id number, transaction_time timestamp, recharge_type VARCHAR2(6), recharge_device_id number, PRIMARY KEY(recharge_id), FOREIGN KEY(wallet_id) REFERENCES WALLET(wallet_id), FOREIGN KEY(recharge_device_id) REFERENCES RECHARGE_DEVICE(recharge_device_id), CONSTRAINT recharge_type_options CHECK (recharge_type in ('Top-up','Ride','Pass')));
CREATE TABLE PASS_TYPE(pass_type_id number GENERATED BY DEFAULT AS IDENTITY, price number, no_of_days number, name varchar(12), PRIMARY KEY(pass_type_id));
CREATE TABLE PASS(pass_id number GENERATED BY DEFAULT AS IDENTITY, card_id number, pass_expiry date, pass_type_id number, valid_from date, recharge_id number, PRIMARY KEY(pass_id), FOREIGN KEY(card_id) REFERENCES CARD(card_id), FOREIGN KEY(pass_type_id) REFERENCES PASS_TYPE(pass_type_id), FOREIGN KEY(recharge_id) REFERENCES RECHARGE(recharge_id));
CREATE TABLE LINE(line_id number GENERATED BY DEFAULT AS IDENTITY, transit_id number, name varchar (30), start_date timestamp, PRIMARY KEY(line_id), FOREIGN KEY(transit_id) REFERENCES TRANSIT(transit_id));
CREATE TABLE TRANSACTION_DEVICE(transaction_device_id number GENERATED BY DEFAULT AS IDENTITY, station_id number, line_id number, status varchar2(8), PRIMARY KEY(transaction_device_id), FOREIGN KEY (station_id) REFERENCES STATION(station_id), FOREIGN KEY (line_id) REFERENCES LINE(line_id),  CONSTRAINT transaction_device_status_options CHECK (status in ('Active','Inactive')));
CREATE TABLE TRANSACTION(transaction_id number GENERATED BY DEFAULT AS IDENTITY, transaction_type varchar(10), swipe_time timestamp, wallet_id number not null, value number, transaction_device_id number, PRIMARY KEY(transaction_id), FOREIGN KEY (wallet_id) REFERENCES wallet(wallet_id), FOREIGN KEY (transaction_device_id) REFERENCES TRANSACTION_DEVICE(transaction_device_id), CONSTRAINT transaction_type_option CHECK (transaction_type in ('Pass','Ride','Balance')));
CREATE TABLE LINE_STATION_CONNECTIONS(connection_id number GENERATED BY DEFAULT AS IDENTITY,line_id number,station_id number,PRIMARY KEY(connection_id),FOREIGN KEY(line_id) REFERENCES LINE(line_id), FOREIGN KEY(station_id) REFERENCES STATION(station_id));
CREATE TABLE OPERATIONS(operation_id number GENERATED BY DEFAULT AS IDENTITY, start_time timestamp, end_time timestamp, reason varchar(50), 
log_timestamp timestamp, transit_id number, line_id number, station_id number,recharge_device_id number, transaction_device_id number, PRIMARY KEY(operation_id),FOREIGN KEY(transit_id) REFERENCES Transit(transit_id),FOREIGN KEY(line_id) REFERENCES Line(line_id),FOREIGN KEY (station_id) REFERENCES STATION(station_id), FOREIGN KEY (recharge_device_id) REFERENCES RECHARGE_DEVICE(Recharge_Device_id),FOREIGN KEY(transaction_device_id) REFERENCES Transaction_device(transaction_device_id));
/
insert into TRANSIT (transit_id, name, status , start_date, price_per_ride)
select 1, 'Subway', 'Active', to_date('16-01-2000','dd-mm-yyyy'), 2.9 from dual union all
select 2, 'Bus', 'Active', to_date('29-01-2000','dd-mm-yyyy'), 1.9 from dual union all
select 3, 'Commuter Rail', 'Active', to_date('20-01-2000','dd-mm-yyyy'), 10 from dual union all
select 4, 'Ferry', 'Inactive', to_date('30-01-2000','dd-mm-yyyy'), 30 from dual;

insert into WALLET(wallet_id, wallet_type, wallet_expiry, start_date, status)
select 1, 'Card', to_date('16-01-2022','dd-mm-yyyy'), to_date('16-09-2025','dd-mm-yyyy'), 'Active' from dual union all
select 2, 'Ticket', to_date('01-01-2023','dd-mm-yyyy'), to_date('16-02-2023','dd-mm-yyyy'), 'Active' from dual union all
select 3, 'Card', to_date('09-04-2020','dd-mm-yyyy'), to_date('19-09-2025','dd-mm-yyyy'), 'Active' from dual union all
select 4, 'Ticket', to_date('01-01-2023','dd-mm-yyyy'), to_date('26-02-2023','dd-mm-yyyy'), 'Active' from dual union all
select 5, 'Card', to_date('09-09-2020','dd-mm-yyyy'), to_date('16-09-2025','dd-mm-yyyy'), 'Active' from dual union all
select 6, 'Ticket', to_date('31-01-2020','dd-mm-yyyy'), to_date('06-02-2020','dd-mm-yyyy'), 'Inactive' from dual union all
select 7, 'Card', to_date('31-01-2020','dd-mm-yyyy'), to_date('16-09-2022','dd-mm-yyyy'), 'Inactive' from dual union all
select 8, 'Ticket', to_date('16-09-2020','dd-mm-yyyy'), to_date('29-09-2020','dd-mm-yyyy'), 'Inactive' from dual;

insert into TICKET (ticket_id, wallet_id, rides, transit_id)
select 1,2,4,1 from dual union all
select 2,4,2,1 from dual union all
select 3,6,4,1 from dual union all
select 4,8,2,2 from dual;

insert into STATION (station_id, name, construction_date)
select 1,'Ruggles', to_date('29-01-2000','dd-mm-yyyy') from dual union all
select 2,'BackBay', to_date('29-01-2000','dd-mm-yyyy') from dual union all
select 3,'Chinatown', to_date('29-01-2000','dd-mm-yyyy') from dual union all
select 4,'Downtown Crossing', to_date('29-01-2000','dd-mm-yyyy') from dual union all
select 5,'ForestHill', to_date('29-01-2000','dd-mm-yyyy') from dual union all
select 6,'Government Centre', to_date('29-01-2000','dd-mm-yyyy') from dual union all
select 7,'Kenmore', to_date('30-01-2000','dd-mm-yyyy') from dual; 

insert into CARD (card_id, balance, wallet_id)
select 1,24.00,1 from dual union all
select 2,9.60,3 from dual union all
select 3,14.40,5 from dual union all
select 4,4.80,7 from dual;

insert into RECHARGE_DEVICE (recharge_device_id, station_id, status) 
select 1,2, 'Active' from dual union all
select 2,1, 'Active' from dual union all
select 3,2, 'Active' from dual union all
select 4,4, 'Active' from dual union all
select 5,3, 'Active' from dual union all
select 6,5, 'Active' from dual union all
select 7,7, 'Active' from dual union all
select 8,1, 'Active' from dual union all
select 9,6, 'Inactive' from dual;


insert into RECHARGE (recharge_id, value_of_transaction, wallet_id, transaction_time, recharge_type, recharge_device_id)
select 1, 2.9, 2, to_date('010120 12:00:00','DDMMYY HH24:MI:SS'), 'Ride', 1 from dual union all
select 2, 10, 1, to_date('010120 11:00:00','DDMMYY HH24:MI:SS'), 'Pass', 1 from dual union all
select 3, 180, 3, to_date('010120 10:00:00','DDMMYY HH24:MI:SS'), 'Pass', 1 from dual union all
select 4, 5, 5, to_date('010120 09:00:00','DDMMYY HH24:MI:SS'), 'Top-up', 1 from dual union all
select 5, 2.9, 4, to_date('010120 12:00:00','DDMMYY HH24:MI:SS'), 'Ride', 1 from dual;

insert into PASS_TYPE(pass_type_id, price, no_of_days, name)
select 1,10, 1, '1-day' from dual union all
select 2, 90,7, '7-day' from dual union all
select 3, 180,30, '180-day' from dual;


insert into PASS(pass_id, card_id, pass_expiry, pass_type_id, valid_from, recharge_id)
select 1, 1, to_date('07-02-2023','dd-mm-yyyy'), 1, to_date('01-02-2022','dd-mm-yyyy'), 2 from dual union all
select 2, 3, to_date('01-06-2023','dd-mm-yyyy'), 3,  to_date('01-1-2023','dd-mm-yyyy'),3 from dual;

insert into LINE (line_id, transit_id, name, start_date)
select 1,1,'Orange line',  to_date('01-01-1980','dd-mm-yyyy') from dual union all
select 2,1,'Red line', to_date('01-01-1981','dd-mm-yyyy') from dual union all
select 3,1,'Green line', to_date('01-01-1982','dd-mm-yyyy') from dual union all
select 4,2,'Route 57', to_date('06-01-2000','dd-mm-yyyy') from dual union all
select 5,2,'Route 66', to_date('30-01-2000','dd-mm-yyyy') from dual;

insert into TRANSACTION_DEVICE (transaction_device_id,station_id, line_id, status)
select 1,2,3,'Active' from dual union all
select 2,1,2,'Inactive' from dual;

insert into TRANSACTION(transaction_id, transaction_type, swipe_time, wallet_id, value, transaction_device_id)
select 1, 'Balance', to_date('010120 12:00:00','DDMMYY HH24:MI:SS'), 1, 20, 1 from dual union all
select 2, 'Ride', to_date('010120 11:00:00','DDMMYY HH24:MI:SS'), 2, 30, 2 from dual union all
select 3, 'Pass', to_date('010120 11:00:00','DDMMYY HH24:MI:SS'), 1, 30, 1 from dual;

insert into LINE_STATION_CONNECTIONS (connection_id, line_id, station_id)
select 1,2,3 from dual union all
select 2,2,2 from dual union all
select 3,3,1 from dual;

insert into OPERATIONS ( operation_id, start_time, end_time, reason, log_timestamp, transit_id, line_id, station_id, recharge_device_id, transaction_device_id) 
select 1,to_date('010123 01:00:00','DDMMYY HH24:MI:SS'), to_date('010123 05:00:00','DDMMYY HH24:MI:SS'), 'Maintenance', CURRENT_TIMESTAMP, 1, NULL, NULL, NULL, NULL from dual union all
select 2,to_date('010124 11:00:00','DDMMYY HH24:MI:SS'), to_date('010122 19:00:00','DDMMYY HH24:MI:SS'), 'Maintenance', CURRENT_TIMESTAMP, NULL, 2, NULL, NULL, NULL from dual;

/
